regions:
  ams:
    name: Amsterdam, Netherlands
    lat: 52.374344
    lon: 4.895439
    map: eu
    x: 325.62897709065885
    y: 227.85920498623625
  iad:
    name: Ashburn, Virginia (US)
    lat: 39.02214
    lon: -77.462555
    map: us
    x: 753.3598022258124
    y: 218.05721663167571
  atl:
    name: Atlanta, Georgia (US)
    lat: 33.6407
    lon: -84.4277
    map: us
    x: 666.8622894496666
    y: 334.50323467265434
  bos:
    name: Boston, Massachusetts (US)
    lat: 42.366978
    lon: -71.02236
    map: us
    x: 827.1098175107608
    y: 136.23009703027913
  ord:
    name: Chicago, Illinois (US)
    lat: 41.891544
    lon: -87.63039
    map: us
    x: 604.0234830583017
    y: 184.81812492869688
  dfw:
    name: Dallas, Texas (US)
    lat: 32.778286
    lon: -96.7984
    map: us
    x: 476.1993201496286
    y: 361.5248496538476
  mia:
    name: Miami, Florida (US)
    lat: 25.7877
    lon: -80.2241
    map: us
    x: 755.3064170132483
    y: 469.82316642663625
  sjc:
    name: San Jose, California (US)
    lat: 37.3516
    lon: -121.89674
    map: us
    x: 112.63114487340647
    y: 223.9075025700198
  sea:
    name: Seattle, Washington (US)
    lat: 47.6097
    lon: -122.3331
    map: us
    x: 159.108421435958
    y: 37.01944688208971
  ewr:
    name: Secaucus, NJ (US)
    lat: 40.789543
    lon: -74.05653
    map: us
    x: 793.5743604788862
    y: 175.28796263135462
  syd:
    name: Sydney, Australia
    lat: -33.86603
    lon: 151.20692
    map: au
    x: 534.6930403393228
    y: 372.7978615141456
studios:
  adelaide:
    lat: -34.9281805
    lon: 138.5999312
    map: au
    x: 398.4384995267775
    y: 372.66189890178106
  alexandria:
    lat: 38.805
    lon: -77.043
    map: us
    x: 760.083179034975
    y: 220.88885532144934
  annapolis:
    lat: 38.977
    lon: -76.49
    map: us
    x: 767.2299344207813
    y: 216.11177407681362
  ashburn:
    lat: 39.030019100000004
    lon: -77.46964646557657
    map: us
    x: 753.2310471605465
    y: 217.93121649798343
  austin:
    lat: 30.268
    lon: -97.743
    map: us
    x: 460.5946026114453
    y: 408.3844834496065
  bellevue:
    lat: 47.6144219
    lon: -122.192337
    map: us
    x: 160.84891797792403
    y: 37.4219765697967
  boston:
    lat: 42.3554334
    lon: -71.060511
    map: us
    x: 826.661092211232
    y: 136.57544481515015
  carmel:
    lat: 39.978
    lon: -86.126
    map: us
    x: 628.4271325916611
    y: 218.66736359890683
  cary:
    lat: 35.79
    lon: -78.781
    map: us
    x: 745.7286718838117
    y: 281.54568667130036
  charlotte:
    lat: 35.223
    lon: -80.838
    map: us
    x: 716.9949924630313
    y: 297.3280639322754
  chicago:
    lat: 41.884
    lon: -87.632
    map: us
    x: 604.0138271084311
    y: 184.96143997309503
  clearwater:
    lat: 27.966
    lon: -82.796
    map: us
    x: 706.5473236124388
    y: 436.43303362885484
  coquitlam:
    lat: 49.2842958
    lon: -122.793281
    map: us
    x: 162.11317965957727
    y: 5.675253914880955
  cranford:
    lat: 40.6584358
    lon: -74.2995923
    map: us
    x: 790.815075673393
    y: 178.46885561265594
  dayton:
    lat: 39.759
    lon: -84.194
    map: us
    x: 656.1568422996456
    y: 219.64530171816716
  durham:
    lat: 35.995
    lon: -78.897
    map: us
    x: 743.3241585423084
    y: 278.05716284229277
  everett:
    lat: 47.9793437
    lon: -122.2127011
    map: us
    x: 162.44243958813217
    y: 30.84344800516351
  folsom:
    lat: 38.6779591
    lon: -121.176058
    map: us
    x: 129.39451571700687
    y: 202.57986287602603
  glenview:
    lat: 42.078
    lon: -87.799
    map: us
    x: 601.4030344287673
    y: 181.52679166478015
  greenhills:
    lat: 36.105
    lon: -86.815
    map: us
    x: 625.7519967420483
    y: 292.3296808842899
  harrisburg:
    lat: 40.26
    lon: -76.882
    map: us
    x: 756.8774021217204
    y: 193.55267565048007
  kennesaw:
    lat: 34.023
    lon: -84.616
    map: us
    x: 663.1172630068728
    y: 327.71284702649643
  lakeview:
    lat: 42.254
    lon: -88.001
    map: us
    x: 598.3544936057206
    y: 178.4656881939419
  laval:
    lat: 45.6066
    lon: -73.707092
    map: us
    x: 777.3324153383578
    y: 86.23752866493703
  lincolnshire:
    lat: 42.1900249
    lon: -87.9084039
    map: us
    x: 599.723541646565
    y: 179.55673222553196
  livermore:
    lat: 37.676
    lon: -121.759
    map: us
    x: 116.2196000467979
    y: 218.55680408776743
  lwr:
    lat: 27.409191200000002
    lon: -82.39252437499218
    map: us
    x: 714.6376165537483
    y: 445.74101093532545
  manchester:
    lat: 42.9956
    lon: -71.4548
    map: us
    x: 818.3657544827604
    y: 126.33737918952897
  mdballroom:
    lat: 29.7589382
    lon: -95.3676974
    map: us
    x: 498.90549219956324
    y: 418.12500231765466
  merrillville:
    lat: 41.48281
    lon: -87.33281
    map: us
    x: 608.8143728778319
    y: 192.10923916192849
  millbrae:
    lat: 37.598958
    lon: -122.400941
    map: us
    x: 106.77652299796523
    y: 217.4079077133133
  monterey:
    lat: 36.2231079
    lon: -121.387742
    map: us
    x: 114.22735431477787
    y: 246.42461952761005
  montgomery:
    lat: 39.6837328
    lon: -84.2854817
    map: us
    x: 655.0399803947201
    y: 221.2138588769975
  montreal:
    lat: 45.5019
    lon: -73.5674
    map: us
    x: 779.5648385687444
    y: 87.71272338612823
  perth:
    lat: -31.9558933
    lon: 115.8605855
    map: au
    x: 150.64824841659464
    y: 343.5284632499252
  petaluma:
    lat: 38.295411
    lon: -122.61369350203252
    map: us
    x: 107.4094830912855
    y: 203.92725719975465
  raleigh:
    lat: 35.785
    lon: -78.643
    map: us
    x: 747.7831716008914
    y: 281.2636146992004
  richmond:
    lat: 37.541
    lon: -77.434
    map: us
    x: 759.1837835261686
    y: 245.37727238439845
  ridgewood:
    lat: 40.9796683
    lon: -74.1194403
    map: us
    x: 791.8986820872547
    y: 172.00343906758667
  roanoke:
    lat: 37.272
    lon: -79.941
    map: us
    x: 723.8834608954846
    y: 257.0370360397393
  salem:
    lat: 44.933
    lon: -123.04
    map: us
    x: 136.50150209185773
    y: 82.40005410159029
  sanjose:
    lat: 37.3361663
    lon: -121.890591
    map: us
    x: 112.63990545612671
    y: 224.21213764765776
  sarasota:
    lat: 27.339
    lon: -82.539
    map: us
    x: 712.4055629423673
    y: 447.3783588884137
  schaumburg:
    lat: 42.0333608
    lon: -88.083406
    map: us
    x: 597.572238623354
    y: 182.69493513723273
  slc:
    lat: 40.7608
    lon: -111.891
    map: us
    x: 266.82050091642657
    y: 192.5966797377855
  stockton:
    lat: 37.9577016
    lon: -121.290779
    map: us
    x: 124.22437620496748
    y: 215.2498229960346
  sugarland:
    lat: 29.633
    lon: -95.601
    map: us
    x: 495.13521982938465
    y: 420.4983994549814
  sydney:
    lat: -33.8302783
    lon: 151.1570269
    map: au
    x: 534.230562541865
    y: 372.2557543437587
  vabeach:
    lat: 36.755
    lon: -76.06
    map: us
    x: 782.006683846955
    y: 255.8200576232449
  vicenza:
    lat: 45.63485905
    lon: 11.40635425660249
    map: eu
    x: 378.56562289553625
    y: 351.4769758208661
  warsaw:
    lat: 52.2319581
    lon: 21.0067249
    map: eu
    x: 490.39324839414974
    y: 246.01935311424063
  westchester:
    lat: 39.3303357
    lon: -84.408275
    map: us
    x: 654.1151636067387
    y: 228.04018651927674
  woodlands:
    lat: 30.158
    lon: -95.456
    map: us
    x: 497.43205315199447
    y: 410.674112886692
