---
2025:
  abq:
    :name: Albuquerque
    :region: dfw
    :events:
      freestyle:
        :name: Freestyle
      showcase:
        :name: Showcase
      medal-ball:
        :name: Medal Ball
  adelaide:
    :name: Adelaide
    :region: syd
    :locale: en-AU
    :events:
      adelaide-combined:
        :name: Adelaide Combined
      adelaide-local:
        :name: Adelaide Local
      northside:
        :name: Northside
      inner-west:
        :name: Inner West
      inner-west-special:
        :name: Inner West Special
  annapolis:
    :name: Annapolis
    :region: iad
    :events:
      medal-ball:
        :name: Medal Ball
      chesapeake-classic:
        :name: Chesapeake Classic
      movie-madness:
        :name: Movie Madness
      gratitude-gala:
        :name: Gratitude Gala
  barcelona:
    :name: Barcelona
    :region: ams
    :locale: es-ES
    :events:
      april:
        :name: April
      may:
        :name: May
      june:
        :name: June
      july:
        :name: July
      august:
        :name: August
      september:
        :name: September
      october:
        :name: October
      november:
        :name: November
      december:
        :name: December
  bellevue:
    :name: Bellevue
    :region: sea
    :events:
      hawaii:
        :name: Hawaii
      winter:
        :name: Winter
      summer-medal-ball:
        :name: Summer Medal Ball
      summer-showcase:
        :name: Summer Showcase
  boston:
    :name: Boston
    :region: bos
    :events:
      april:
        :name: April
      mini-comp:
        :name: Mini Comp
      october:
        :name: October
  carmel:
    :name: Carmel
    :region: ord
    :events:
      paint-the-town-red:
        :name: Paint the Town Red
      toys-to-life:
        :name: Toys to Life
  charlotte:
    :name: Charlotte
    :region: atl
  chicago:
    :name: Chicago
    :region: ord
  clearwater:
    :name: Clearwater
    :region: mia
    :events:
      valentines-opener:
        :name: Valentine’s Opener
      portland-opener:
        :name: Portland Opener
      beach-ball:
        :name: Beach Ball
      unique-opener:
        :name: Unique Opener
      national-dance-day:
        :name: National Dance Day
      glass-slipper-gala:
        :name: Glass Slipper Gala
      flamingo-opener:
        :name: Flamingo Opener
      fright-fest:
        :name: Fright Fest
      snowball:
        :name: Snowball
  columbia:
    :name: Columbia
    :region: iad
  coquitlam:
    :name: Coquitlam
    :region: sea
    :locale: en-CA
    :events:
      ballroom-blitz:
        :name: Ballroom Blitz
      showcase:
        :name: Showcase
      showcase-2:
        :name: Showcase 2
      spotlight-ball:
        :name: Spotlight Ball
      medal-ball:
        :name: Medal Ball
  cranford:
    :name: Cranford
    :region: ewr
    :events:
      spring-freestyles:
        :name: Spring Freestyles
      fall-freestyles:
        :name: Fall Freestyles
  dayton:
    :name: Dayton
    :region: ord
  everett:
    :name: Everett
    :region: sea
  firenze:
    :name: Firenze
    :region: ams
    :locale: it-IT
    :events:
      june:
        :name: June
      july:
        :name: July
      august:
        :name: August
      september:
        :name: September
      october:
        :name: October
      november:
        :name: November
      december:
        :name: December
  folsom:
    :name: Folsom
    :region: sjc
  glenview:
    :name: Glenview
    :region: ord
  greenhills:
    :name: Nashville-Green Hills
    :region: atl
    :events:
      spring:
        :name: Spring
      music-city:
        :name: Music City
  harrisburg:
    :name: Harrisburg
    :region: iad
  honolulu:
    :name: Honolulu
    :region: sjc
  kennesaw:
    :name: Kennesaw
    :region: atl
  kobe:
    :name: Kobe
    :region: nrt
    :locale: ja-JP
    :events:
      medal-ball:
        :name: Medal Ball
      yokohama-showcase:
        :name: Yokohama Showcase
      fall-showcase:
        :name: Fall Showcase
  kyiv:
    :name: Kyiv
    :region: ams
    :locale: uk-UA
  lakeview:
    :name: Lakeview
    :region: ord
    :events:
      medal-ball-graduation-night-may:
        :name: Medal Ball Graduation Night - May
      summer-showcase-rounds:
        :name: Summer Showcase Rounds
      summer-showcase:
        :name: Summer Showcase
      showcase-rounds:
        :name: Showcase Rounds
      medal-ball-graduation-night-nov:
        :name: Medal Ball Graduation Night - Nov
  laval:
    :name: Laval
    :region: bos
    :locale: fr-CA
  livermore:
    :name: Livermore
    :region: sjc
    :events:
      pep-rally:
        :name: Pep Rally
      the-music-of-prince:
        :name: The Music of Prince
      james-bond:
        :name: James Bond
      extravaganza:
        :name: Extravaganza
      bbq-pep-rally:
        :name: BBQ Pep Rally
      la-la-land:
        :name: La La Land Metal Ball
      district-showcase:
        :name: District Showcase
  marlton:
    :name: Marlton
    :region: ewr
    :events:
      freestyle:
        :name: Freestyle
      medal-ball:
        :name: Medal Ball
  mdballroom:
    :name: Memorial DanceSport Ballroom
    :region: dfw
    :logo: mdballroom.webp
  merrillville:
    :name: Merrillville
    :region: ord
    :events:
      team-match:
        :name: Team Match
      arthur-murray-prom:
        :name: Arthur Murray Prom
      graduation-night:
        :name: Graduation Night
      club-arthur-murray:
        :name: Club Arthur Murray
      harvest-moon:
        :name: Harvest Moon
      winter-wonderland:
        :name: Winter Wonderland
  miami:
    :name: Miami
    :region: mia
    :events:
      april:
        :name: April
      may:
        :name: May
      june:
        :name: June
      july:
        :name: July
      august:
        :name: August
      september:
        :name: September
      october:
        :name: October
      november:
        :name: November
      december:
        :name: December
  milano:
    :name: Milano
    :region: ams
    :locale: it-IT
    :events:
      april:
        :name: April
      may:
        :name: May
      june:
        :name: June
      july:
        :name: July
      august:
        :name: August
      september:
        :name: September
      october:
        :name: October
      november:
        :name: November
      december:
        :name: December
  millbrae:
    :name: Millbrae
    :region: sjc
  montgomery:
    :name: Montgomery
    :region: ord
    :events:
      cddc:
        :name: CDDC
      grand-rapids:
        :name: Grand Rapids
      fall-cddc:
        :name: Fall CDDC
      swing-sway:
        :name: Swing & Sway
      royal-oak:
        :name: Royal Oak
      lincolnshire:
        :name: Lincolnshire
  montreal:
    :name: Montreal
    :region: bos
    :locale: fr-CA
    :events:
      certification-exams:
        :name: Certification Exams
      graduation-ball:
        :name: Graduation Ball
  monza:
    :name: Monza
    :region: ams
    :locale: it-IT
    :events:
      april:
        :name: April
      may:
        :name: May
      june:
        :name: June
      july:
        :name: July
      august:
        :name: August
      september:
        :name: September
      october:
        :name: October
      november:
        :name: November
      december:
        :name: December
  princeton:
    :name: Princeton
    :region: ewr
  raleigh:
    :name: Raleigh
    :region: iad
    :events:
      disney:
        :name: Disney
      team-match:
        :name: Team Match
      shimmer-shine:
        :name: Shimmer & Shine
  reno:
    :name: Reno
    :region: sjc
  richmond:
    :name: Richmond
    :region: atl
    :events:
      medal-ball:
        :name: Medal Ball
      team-match:
        :name: Team Match
      nouveau-duo:
        :name: Nouveau Duo
  salem:
    :name: Salem
    :region: sea
    :events:
      spring:
        :name: Spring
      fall:
        :name: Fall
  sanjose:
    :name: San Jose
    :region: sjc
    :events:
      march:
        :name: March
      september:
        :name: September
  slc:
    :name: Salt Lake City
    :region: sjc
    :events:
      winter-wonderland:
        :name: Winter Wonderland
      medal-ball:
        :name: Medal Ball
      extravaganza:
        :name: Extravaganza
      medal-ball-august:
        :name: Medal Ball August
  stockton:
    :name: Stockton
    :region: sjc
    :events:
      mdna-medal-ball:
        :name: MDNA Medal Ball
      beach-ball:
        :name: Beach Ball
      extravaganza:
        :name: Extravaganza
      medal-ball:
        :name: Medal Ball
  sugarland:
    :name: Sugar Land
    :region: dfw
    :events:
      jingle-ball:
        :name: Jingle Ball
      summer:
        :name: Summer
  sydney:
    :name: Sydney
    :region: syd
    :locale: en-AU
    :events:
      rhythm:
        :name: Rhythm
      winter:
        :name: Winter
  torino:
    :name: Torino
    :region: ams
    :locale: it-IT
    :events:
      april:
        :name: April
      may:
        :name: May
      june:
        :name: June
      july:
        :name: July
      august:
        :name: August
      september:
        :name: September
      october:
        :name: October
      november:
        :name: November
      december:
        :name: December
  vabeach:
    :name: Virginia Beach
    :region: iad
    :events:
      medal-ball:
        :name: Medal Ball
      beach-bash:
        :name: Beach Bash
      freestyles:
        :name: Freestyles
  vegas:
    :name: Las Vegas
    :region: sjc
  vicenza:
    :name: Vicenza
    :region: ams
    :locale: it-IT
    :events:
      april:
        :name: April
      may:
        :name: May
      june:
        :name: June
      july:
        :name: July
      august:
        :name: August
      september:
        :name: September
      october:
        :name: October
      november:
        :name: November
      december:
        :name: December
  warsaw:
    :name: Warsaw
    :region: ams
    :locale: pl-PL
    :events:
      wroclaw:
        :name: Wroclaw
      warsaw:
        :name: Warsaw
  woodlands:
    :name: Woodlands
    :region: dfw
2024:
  adelaide:
    :name: Adelaide
    :region: syd
    :locale: en-AU
    :events:
      starry-night:
        :name: Starry Night
      rewind:
        :name: Rewind
      northside:
        :name: Northside
      adalaide:
        :name: Adalaide
  alexandria:
    :name: Alexandria
    :region: iad
  annapolis:
    :name: Annapolis
    :region: iad
    :events:
      medalball:
        :name: Metal Ball
      chesapeakeclassic:
        :name: Chesapeake Classic
      gratitudegala:
        :name: Gratitude Gala
  austin:
    :name: Austin
    :region: dfw
  bellevue:
    :name: Bellevue
    :region: sea
    :events:
      june-medal-ball:
        :name: June Medal Ball
      august-showcase:
        :name: August Showcase
      october-mini-comp:
        :name: October Mini Comp
      spotlight-ball:
        :name: Spotlight ball
      december-medal-ball:
        :name: December Medal Ball
  boston:
    :name: Boston
    :region: bos
  carmel:
    :name: Carmel
    :region: ord
    :events:
      spring-showcase:
        :name: Spring Showcase
      back-to-the-80s:
        :name: Back to the 80’s
  cary:
    :name: Cary
    :region: iad
  charlotte:
    :name: Charlotte
    :region: atl
  chicago:
    :name: Chicago
    :region: ord
  clearwater:
    :name: Clearwater
    :region: mia
    :events:
      texas-opener:
        :name: Texas Opener
      birthday-bash:
        :name: Birthday Bash
      glass-slipper:
        :name: Glass Slipper Gala
      northstar-opener:
        :name: Northstar Opener
      flamingo-opener:
        :name: Flamingo Opener
      fright-fest:
        :name: Fright Fest
      snowball:
        :name: Snowball
  cranford:
    :name: Cranford
    :region: ewr
    :events:
      spring-freestyles:
        :name: Spring Freestyles
      fall-freestyles:
        :name: Fall Freestyles
  dayton:
    :name: Dayton
    :region: ord
  durham:
    :name: Durham
    :region: iad
  everett:
    :name: Everett
    :region: sea
  glenview:
    :name: Glenview
    :region: ord
    :events:
      chicagoland-feb:
        :name: Chicagoland Feb
      chicagoland-sept:
        :name: Chicagoland Sept
  greenhills:
    :name: Nashville-Green Hills
    :region: atl
    :events:
      spring:
        :name: Spring
      music-city:
        :name: Music City
      revival:
        :name: Revival
  harrisburg:
    :name: Harrisburg
    :region: iad
  kennesaw:
    :name: Kennesaw
    :region: atl
  kyiv:
    :name: Kyiv
    :region: ams
    :locale: uk-UA
    :events:
      july:
        :name: July
      freestyle-showcase:
        :name: Freestyle Showcase
  lakeview:
    :name: Lakeview
    :region: ord
    :events:
      showcase-rounds:
        :name: Showcase Rounds
      graduation-nights:
        :name: Graduation Nights
      in-studio:
        :name: In Studio
      showcase-rounds-september:
        :name: Showcase Rounds - September
      graduation-nights-2:
        :name: Graduation Nights 2
  laval:
    :name: Laval
    :region: bos
    :locale: fr-CA
  lincolnshire:
    :name: Lincolnshire
    :region: ord
  livermore:
    :name: Livermore
    :region: sjc
    :events:
      pep-rally:
        :name: Pep Rally
      district-showcase:
        :name: District Showcase
      barbecue-pep-rally:
        :name: Barbecue Pep Rally
      live-medal-ball:
        :name: Live Medal Ball
      willie-wonkas-magical-night:
        :name: Willie Wonka’s Magical Night
      extravaganza:
        :name: Extravaganza
  lwr:
    :name: Lakewood Ranch
    :region: mia
  manchester:
    :name: Manchester
    :region: bos
  mdballroom:
    :name: Memorial DanceSport Ballroom
    :region: dfw
    :logo: mdballroom.webp
    :events:
      february-team-match:
        :name: February Team Match
      june-team-match:
        :name: June Team Match
  merrillville:
    :name: Merrillville
    :region: ord
    :events:
      medal-ball:
        :name: Medal Ball
      team-match:
        :name: Team Match
      graduation-night:
        :name: Graduation Night
      newsome-twosome:
        :name: Newsome Twosome
      snowball-spotlight:
        :name: Snowball Spotlight
  monterey:
    :name: Monterey
    :region: sjc
  montgomery:
    :name: Montgomery
    :region: ord
    :events:
      dreamland:
        :name: Dreamland
      fort-wayne:
        :name: Fort Wayne
      cddc:
        :name: CDDC
      swing-sway:
        :name: Swing & Sway
  montreal:
    :name: Montreal
    :region: bos
    :locale: fr-CA
    :events:
      june:
        :name: June
      november:
        :name: November
      december:
        :name: December
  perth:
    :name: Perth
    :region: syd
    :locale: en-AU
    :events:
      karaoke:
        :name: Karaoke
      country:
        :name: Country
      pin-up-50s:
        :name: Pin Up 50's
      hawaiian:
        :name: Hawaiian
      christmas:
        :name: Christmas
  petaluma:
    :name: Petaluma
    :region: sjc
  raleigh:
    :name: Raleigh
    :region: iad
    :events:
      casino-royale:
        :name: Casino Royale
      in-house:
        :name: In House
  richmond:
    :name: Richmond
    :region: atl
    :events:
      medal-ball:
        :name: Medal Ball
      team-match:
        :name: Team Match
      nouveau-duo:
        :name: Nouveau Duo
  ridgewood:
    :name: Ridgewood
    :region: ewr
  roanoke:
    :name: Roanoke
    :region: iad
    :events:
      team-match:
        :name: Team Match
      spring-showcase:
        :name: Spring Showcase
      medal-ball:
        :name: Medal Ball
      fall-showcase:
        :name: Fall Showcase
  salem:
    :name: Salem
    :region: sea
    :events:
      spring:
        :name: Spring
      fall:
        :name: Fall
  sanjose:
    :name: San Jose
    :region: sjc
    :events:
      march:
        :name: March
      september:
        :name: September
  sarasota:
    :name: Sarasota
    :region: mia
  schaumburg:
    :name: Schaumburg
    :region: ord
  slc:
    :name: Salt Lake City
    :region: sjc
    :events:
      june:
        :name: June
      medal-ball:
        :name: Medal Ball
  stockton:
    :name: Stockton
    :region: sjc
    :events:
      walk-this-way:
        :name: Walk This Way
      dance-down-memory-lane:
        :name: Dance Down Memory Lane
  sugarland:
    :name: Sugar Land
    :region: dfw
  sydney:
    :name: Sydney
    :region: syd
    :locale: en-AU
    :events:
      gatsby:
        :name: Gatsby
      dancing-with-the-stars:
        :name: Dancing With The Stars
  vabeach:
    :name: Virginia Beach
    :region: iad
    :events:
      newsome-twosome:
        :name: Medal Ball - Newsome Twosome
      summer-beach-bash:
        :name: Summer Beach Bash
      freestyles:
        :name: Virginia Beach Freestyles
  vicenza:
    :name: Vicenza
    :region: ams
    :locale: it-IT
  warsaw:
    :name: Warsaw
    :region: ams
    :locale: pl-PL
    :events:
      june-warsaw-freestyle:
        :name: June Warsaw Freestyle
      freestyle-showcase-warsaw-2024:
        :name: Freestyle Showcase Warsaw 2024
  westchester:
    :name: West Chester
    :region: ord
  woodlands:
    :name: Woodlands
    :region: dfw
2023:
  annapolis:
    :name: Annapolis
    :region: iad
    :events:
      medalball:
        :name: Metal Ball
      chesapeakeclassic:
        :name: Chesapeake Classic
      gratitudegala:
        :name: Gratitude Gala
  carmel:
    :name: Carmel
    :region: ord
  charlotte:
    :name: Charlotte
    :region: atl
  chicago:
    :name: Chicago
    :region: ord
  clearwater:
    :name: Clearwater
    :region: mia
    :events:
      glassslipper:
        :name: Glass Slipper Gala
      nationaldance:
        :name: National Dance Day
      flamingoopener:
        :name: Flamingo Opener
      flamingo-fright:
        :name: Flamingo Fright Festival
      snowball:
        :name: Snowball
  durham:
    :name: Durham
    :region: iad
  greenhills:
    :name: Nashville-Green Hills
    :region: atl
  harrisburg:
    :name: Harrisburg
    :region: iad
  kennesaw:
    :name: Kennesaw
    :region: atl
  lakeview:
    :name: Lakeview
    :region: ord
    :events:
      showcase:
        :name: Showcase
      showcase-rounds:
        :name: Showcase Rounds
  livermore:
    :name: Livermore
    :region: sjc
  montreal:
    :name: Montreal
    :region: bos
    :locale: fr-CA
  raleigh:
    :name: Raleigh
    :region: iad
    :events:
      night-in-paris:
        :name: A Night In Paris
      team-match:
        :name: Team Match
  richmond:
    :name: Richmond
    :region: atl
    :events:
      medalball:
        :name: Medal Ball
      teammatch:
        :name: Team Match
      nouveau-duo:
        :name: Nouveau Duo
  salem:
    :name: Salem
    :region: sea
  sarasota:
    :name: Sarasota
    :region: mia
  sugarland:
    :name: Sugar Land
    :region: dfw
  sydney:
    :name: Sydney
    :region: syd
    :locale: en-AU
  vabeach:
    :name: Virginia Beach
    :region: iad
  woodlands:
    :name: Woodlands
    :region: dfw
2022:
  annapolis:
    :name: Annapolis
    :region: iad
    :events:
      medalball:
        :name: Metal Ball
      chesapeakeclassic:
        :name: Chesapeake Classic
      gratitudegala:
        :name: Gratitude Gala
  cary:
    :name: Cary
    :region: iad
  charlotte:
    :name: Charlotte
    :region: atl
  harrisburg:
    :name: Harrisburg
    :region: iad
  kennesaw:
    :name: Kennesaw
    :region: atl
  vabeach:
    :name: Virginia Beach
    :region: iad
